/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pratikum180626;

import javax.swing.JOptionPane;

/**
 *
 * @author Mutiara Yulianda
 */
public class FormNilai extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormNilai.class.getName());

    /**
     * Creates new form FormNilai
     */
    public FormNilai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblForm = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblKelas = new javax.swing.JLabel();
        lblMatkul = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtKelas = new javax.swing.JTextField();
        txtMatkul = new javax.swing.JTextField();
        lblQuiz = new javax.swing.JLabel();
        lblTugas = new javax.swing.JLabel();
        lblUts = new javax.swing.JLabel();
        lblUas = new javax.swing.JLabel();
        txtQuiz = new javax.swing.JTextField();
        txtTugas = new javax.swing.JTextField();
        txtUts = new javax.swing.JTextField();
        txtUas = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        lblNilai = new javax.swing.JLabel();
        lblKonversi = new javax.swing.JLabel();
        txtNilai = new javax.swing.JTextField();
        txtKonversi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblForm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblForm.setText("FORM PENILAIAN MAHASISWA");

        lblNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNama.setText("Nama Mahasiswa ");

        lblKelas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblKelas.setText("Kelas ");

        lblMatkul.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMatkul.setText("Mata Kuliah ");

        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtKelas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtMatkul.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblQuiz.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQuiz.setText("Nilai Quiz");

        lblTugas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTugas.setText("Nilai Tugas ");

        lblUts.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUts.setText("Nilai UTS ");

        lblUas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUas.setText("Nilai UAS ");

        txtQuiz.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtTugas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtUts.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtUas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnProses.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnProses.setText("Proses");
        btnProses.addActionListener(this::btnProsesActionPerformed);

        lblNilai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNilai.setText("Nilai Akhir");

        lblKonversi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblKonversi.setText("Konversi Nilai");

        txtNilai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtKonversi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNama)
                    .addComponent(lblKelas)
                    .addComponent(lblMatkul)
                    .addComponent(lblQuiz)
                    .addComponent(lblTugas)
                    .addComponent(lblUts)
                    .addComponent(lblUas))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMatkul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(txtTugas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUts, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKelas, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNilai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKonversi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKonversi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNilai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProses)
                        .addGap(89, 89, 89))))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(lblForm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNama)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKelas)
                            .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMatkul)
                            .addComponent(txtMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuiz)
                            .addComponent(txtQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProses))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTugas)
                            .addComponent(txtTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUts)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblNilai)
                                .addComponent(txtNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtUts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblUas)
                        .addComponent(txtUas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblKonversi)
                    .addComponent(txtKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
      String nama = txtNama.getText();
      String kelas = txtKelas.getText();
      String matkul = txtMatkul.getText();
      
      if (nama.isEmpty() || kelas.isEmpty() || matkul.isEmpty()){
          JOptionPane.showMessageDialog(this, "Data nama tidak boleh kosong");
          txtNama.requestFocus();
      }
      if(txtQuiz.getText().isEmpty() || txtTugas.getText().isEmpty() || txtUts.getText().isEmpty() || txtUas.getText().isEmpty()){
          JOptionPane.showMessageDialog(this, "Nilai harus diisikan!!");
      }
      try{
          
      double quiz = validasiNilai(txtQuiz.getText(), "Quiz");
      double tugas =  validasiNilai(txtTugas.getText(), "Tugas");
      double uts  =  validasiNilai(txtUts.getText(), "UTS");
      double uas =  validasiNilai(txtUas.getText(), "UAS");
      
      
      
      double na = 0.15*quiz + 0.2*tugas + 0.3*uts + 0.35*uas;
      txtNilai.setText(Double.toString(na));
      txtKonversi.setText(KonversiNilai(na));
      
      JOptionPane.showMessageDialog(this,
              "\nNama "+nama+ "\nKelas "+kelas+
              "\nMendapat Nilai "+na+
              "atau setara dengan "+KonversiNilai(na)+
              "\nuntuk mata kuliah "+matkul,
              "Hasil Penilaian", JOptionPane.INFORMATION_MESSAGE);
      
        
        
      }catch(NumberFormatException e){
          JOptionPane.showMessageDialog(this,"Nilai harus berupa angka","Peringatan",JOptionPane.ERROR_MESSAGE);
      }catch (Exception e){
          JOptionPane.showMessageDialog(this, e.getMessage(), "Pengeccekan Nilai", JOptionPane.WARNING_MESSAGE);
      }finally{
           JOptionPane.showMessageDialog(this, "Pengecekan Selesai");
      }
    }
      private double validasiNilai (String input, String jenisNilai) throws Exception{
              double nilai = Double.parseDouble(input);
              if(nilai<0 || nilai > 100)
                  throw new Exception (jenisNilai + "harus antara 0 - 100");
              return nilai;
      
      
    }//GEN-LAST:event_btnProsesActionPerformed
       private String KonversiNilai (double nilai){
           if(nilai >= 80)
              return "A";
           else if (nilai>= 65)
                  return "B";
           else if (nilai >= 55)
                  return "C";
              else if (nilai >= 40)
                  return "D";
              else
                  return "E";
                          
           }
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormNilai().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JLabel lblForm;
    private javax.swing.JLabel lblKelas;
    private javax.swing.JLabel lblKonversi;
    private javax.swing.JLabel lblMatkul;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNilai;
    private javax.swing.JLabel lblQuiz;
    private javax.swing.JLabel lblTugas;
    private javax.swing.JLabel lblUas;
    private javax.swing.JLabel lblUts;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtKonversi;
    private javax.swing.JTextField txtMatkul;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNilai;
    private javax.swing.JTextField txtQuiz;
    private javax.swing.JTextField txtTugas;
    private javax.swing.JTextField txtUas;
    private javax.swing.JTextField txtUts;
    // End of variables declaration//GEN-END:variables
}
